version: '3'
services:
  web-eg:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - ./web/:/opt/web/
    environment:
     - FIC=CYEG
     - CASSANDRA_SERVER=cass-eg
  web-vr:
    build: .
    ports:
     - "5001:5000"
    volumes:
     - ./web/:/opt/web/
    environment:
     - FIC=CYVR
     - CASSANDRA_SERVER=cass-vr
  web-qb:
    build: .
    ports:
     - "5002:5000"
    volumes:
     - ./web/:/opt/web/
    environment:
     - FIC=CYQB
     - CASSANDRA_SERVER=cass-qb
  cass-eg:
    image: cassandra:3
  cass-qb:
    image: cassandra:3
    environment:
     - CASSANDRA_SEEDS=cass-eg
  cass-vr:
    image: cassandra:3
    environment:
     - CASSANDRA_SEEDS=cass-eg
